### ISSUE TITLE
About the label of evaluation dataset

### ISSUE THREAD

**Issue by GilgameshD** [qiuqiangkong/dcase2018_task1#1]
Hi, thanks for sharing your great work!

I notice that there is no label of evaluation dataset (link: https://zenodo.org/record/165995#.W974inr7TEY)

Where can I find these labels ?

Thanks a lot !

**Comment by qiuqiangkong** [comment]
Hi,


    Many thanks! The code is for DCASE 2018 Task 1, the link of data is here http://dcase.community/challenge2018/task-acoustic-scene-classification


Best wishes,


Qiuqiang

________________________________
